# Generated by Django 5.2.4 on 2025-07-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DislikedJob',
            fields=[
                ('disliked_id', models.AutoField(primary_key=True, serialize=False)),
                ('disliked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('salary', models.CharField(blank=True, max_length=100)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LikedJob',
            fields=[
                ('liked_id', models.AutoField(primary_key=True, serialize=False)),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('saved_id', models.AutoField(primary_key=True, serialize=False)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
